name: Publish Docker Image And Deploy

on:
  push:
    branches:
      - main
      - master

env:
  # ghcr 格式如下
  # REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: node-api
  CONTAINER_NAME: node-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 我的服务器目前是用的 腾讯云服务器, 在操作中发现服务器拉取 ghcr 的镜像一直失败，timetout
      # 于是我又切回 docker 官方自带的 hub 了 hub.docker.com
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          # registry: ${{ env.REGISTRY }}
          # username: ${{ github.actor }}
          # password: ${{ secrets.GHCR_TOKEN }}
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PWD }}

      # https://github.com/marketplace/actions/docker-metadata-action#typesha
      # 注意下面这个 action tags 的生成规则
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          images: ${{ secrets.DOCKER_ID }}/${{ env.IMAGE_NAME }}
          tags: type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_UNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [[ -n $(docker ps -q -f "name=${{ env.CONTAINER_NAME }}") ]];then
              docker stop ${{ env.CONTAINER_NAME }}
              docker rm -f ${{ env.CONTAINER_NAME }}
            fi

            docker pull ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
            docker run -d -p 8090:3000 --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_METADATA_OUTPUT_TAGS }}
